const registerUrlMatcher = new RegExp("http://localhost:3000/signup");
const loginUrlMatcher = new RegExp("http://localhost:3000/login");
const basicUrlMatcher = new RegExp("http://localhost:3000/");

describe('Login', function(){
    it('Change to Login Page', function(){
        cy.visit('http://localhost:3000/')
        cy.contains('LOGIN').click()
        cy.url().should('match', basicUrlMatcher);
        cy.visit('http://localhost:3000/login')
        cy.get('[id=email]')
      .type('fake@email.com')
      .should('have.value', 'fake@email.com')
      cy.get('[id=pass]')
      .type('@Sumeela1234')
      .should('have.value', '@Sumeela1234')
      cy.get('[id=sign-in-btn]').click()
    })

    it('Farmer Register', function(){
      cy.visit('http://localhost:3000/')
      cy.contains('Sign Up').click()
      cy.contains('AS FARMER').click()
      cy.url().should('match', new RegExp('http://localhost:3000/farmer/signup'));
      cy.get('[id=firstName]')
      .type('Sumeela')
      .should('have.value', 'Sumeela')
      cy.get('[id=lastName]')
      .type('Madusankha')
      .should('have.value', 'Madusankha')
      cy.get('[id=address]')
      .type('Higurupanagala')
      .should('have.value', 'Higurupanagala')
      cy.get('[id=phone]')
      .type('0766929289')
      .should('have.value', '0766929289')
      cy.get('[id=gsdName]')
      .type('Usamalagoda')
      .should('have.value', 'Usamalagoda')
      cy.get('[id=gsdCode]')
      .type('038605')
      .should('have.value', '038605')
      cy.get('[id=email]')
      .type('sumeela@gmail.com')
      .should('have.value', 'sumeela@gmail.com')
      cy.get('[id=nic]')
      .type('990910820V')
      .should('have.value', '990910820V')
      cy.get('[id=password]')
      .type('@Fake123')
      .should('have.value', '@Fake123')
      cy.get('[id=confPassword]')
      .type('@Fake123')
      .should('have.value', '@Fake123')
    })

    it('Buyer Register', function(){
      cy.visit('http://localhost:3000/')
      cy.contains('Sign Up').click()
      cy.contains('AS BUYER').click()
      cy.url().should('match', new RegExp('http://localhost:3000/buyer/signup'));
      cy.get('[id=firstName]')
      .type('Sumeela')
      .should('have.value', 'Sumeela')
      cy.get('[id=lastName]')
      .type('Madusankha')
      .should('have.value', 'Madusankha')
      cy.get('[id=address]')
      .type('Higurupanagala')
      .should('have.value', 'Higurupanagala')
      cy.get('[id=phone]')
      .type('0766929289')
      .should('have.value', '0766929289')
     
      cy.get('[id=email]')
      .type('sumeela@gmail.com')
      .should('have.value', 'sumeela@gmail.com')
      cy.get('[id=nic]')
      .type('990910820V')
      .should('have.value', '990910820V')
      cy.get('[id=password]')
      .type('@Fake123')
      .should('have.value', '@Fake123')
      cy.get('[id=confPassword]')
      .type('@Fake123')
      .should('have.value', '@Fake123')
    })
    

    it('Crop update UI in farmer', function(){
      cy.visit('http://localhost:3000/')
      cy.contains('LOGIN').click()
      cy.url().should('match', basicUrlMatcher);
      cy.visit('http://localhost:3000/login')
      cy.get('[id=email]')
    .type('farmer1@gmail.com')
    .should('have.value', 'farmer1@gmail.com')
    cy.get('[id=pass]')
    .type('@Farmer123')
    .should('have.value', '@Farmer123')
    cy.get('[id=sign-in-btn]').click()
    cy.contains('Crop Updates').click()
    cy.contains('Completed Tasks').click()

    })
})