import React from 'react';
import Typography from '@mui/material/Typography';

export default function Home() {
    return (
        <Typography color='text.default' margin={40}>
           isudhfisdghfhsgd
           fjhsjdfhgsjdfhgkjfhdkjsdfsudgkmnsbduiaidgjassnbnsdafnbfnbasijnbasfbasfgasnbnfhabsjhgfuajnmasdammnbasjdhgjhnbnbnsafafuunnnbsfdinnbfisudhfisdghfhsgdfjhsjdfhgsjdfhgkjfhdkjsdfsudgkmnsbduiaidgjassnbnsdafnbfnbasijnbasfbasfgasnbnfhabsjhgfuajnmasdammnbasjdhgjhnbnbnsafafuunnnbsfdinnbfisudhfisdghfhsgdfjhsjdfhgsjdfhgkjfhdkjsdfsudgkmnsbduiaidgjassnbnsdafnbfnbasijnbasfbasfgasnbnfhabsjhgfuajnmasdammnbasjdhgjhnbnbnsafafuunnnbsfdinnbfisudhfisdghfhsgdfjhsjdfhgsjdfhgkjfhdkjsdfsudgkmnsbduiaidgjassnbnsdafnbfnbasijnbasfbasfgasnbnfhabsjhgfuajnmasdammnbasjdhgjhnbnbnsafafuunnnbsfdinnbfisudhfisdghfhsgdfjhsjdfhgsjdfhgkjfhdkjsdfsudgkmnsbduiaidgjassnbnsdafnbfnbasijnbasfbasfgasnbnfhabsjhgfuajnmasdammnbasjdhgjhnbnbnsafafuunnnbsfdinnbfisudhfisdghfhsgdfjhsjdfhgsjdfhgkjfhdkjsdfsudgkmnsbduiaidgjassnbnsdafnbfnbasijnbasfbasfgasnbnfhabsjhgfuajnmasdammnbasjdhgjhnbnbnsafafuunnnbsfdinnbfisudhfisdghfhsgdfjhsjdfhgsjdfhgkjfhdkjsdfsudgkmnsbduiaidgjassnbnsdafnbfnbasijnbasfbasfgasnbnfhabsjhgfuajnmasdammnbasjdhgjhnbnbnsafafuunnnbsfdinnbf
        </Typography>
    );
}

